openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: API for managing users and tasks

servers:
  - url: http://localhost:3000/api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: User
    description: User management operations
  - name: Task
    description: Task management operations

paths:
  /register:
    post:
      summary: Register a new user
      tags: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                passwordConfirmation:
                  type: string
      responses:
        '201':
          description: User created successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /login:
    post:
      summary: Login a user
      tags: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User logged in successfully
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Internal server error

  /tasks:
    post:
      summary: Create a new task
      tags: [Task]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                priority:
                  type: string
                status:
                  type: string
      responses:
        '201':
          description: Task created successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
    
    get:
      summary: Get all tasks
      tags: [Task]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of tasks
        '500':
          description: Internal server error

  /tasks/{taskId}:
    get:
      summary: Get a specific task by ID
      tags: [Task]
      security:
        - bearerAuth: []
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID of the task to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Task retrieved successfully
        '404':
          description: Task not found
        '500':
          description: Internal server error

    put:
      summary: Update a specific task by ID
      tags: [Task]
      security:
        - bearerAuth: []
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID of the task to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                priority:
                  type: string
                status:
                  type: string
      responses:
        '204':
          description: Task updated successfully
        '404':
          description: Task not found
        '500':
          description: Internal server error

    delete:
      summary: Delete a specific task by ID
      tags: [Task]
      security:
        - bearerAuth: []
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID of the task to delete
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found
        '500':
          description: Internal server error